chat2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages
  get 'messages/new'

  get 'messages/index'

  root 'messages#index'

end

chat2/app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
end

chat2/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login

validate :validate_username

def validate_username
  if User.where(email: username).exists?
    errors.add(:username, :invalid)
  end
end

  has_many :messages

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
end

chat2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
		devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
	end
end

chat2/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  
  def new
  end

  def index
  	@message = Message.all
  end

  def create
  	@message = Message.new(message_params)

  	@message.save
  	redirect_to :back
  end

  private
  	def message_params
    	params.require(:messages).permit(:name, :content)
  	end
end

chat2/app/helpers/application_helper.rb
module ApplicationHelper
end

chat2/app/helpers/messages_helper.rb
module MessagesHelper
end

chat2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chat2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

chat2/app/views/messages/index.html.erb
<style>
.message {
  height: auto;
  width: 95%;
  margin: 0 auto;
  padding: 10px;
}
.message:nth-child(even) {
  background: #CCCCCC;
}
</style>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= link_to "Uitloggen", destroy_user_session_path, :method => :delete %>
<%= link_to "Profiel aanpassen", edit_user_registration_path %>
<h1>Bericht versturen</h1>
<%= form_tag({controller: "messages", method: "create"}) do %>
  <p>
    <%= hidden_field :messages, :name, :value => current_user.username  %>
  </p>
 
  <p>
    <%= label_tag(:Bericht) %>
    <%= text_field(:messages, :content) %>
  </p>
 
  <p>
    <%= submit_tag("Versturen") %>
  </p>
<% end %>


<h1>Berichten</h1>

<% @message.each do |m| %>
  <div class="message">
    <b><%= m.name %></b><br>
    <%= m.content %><br>
  </div>
<% end %>

chat2/app/views/messages/new.html.erb
<h1>Messages#new</h1>
<%= form_for :message, url: messages_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>